#!/usr/bin/env node
// Convert scratch/central-svg/*.svg into src/components/icons.generated.ts
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
const dir = "scratch/central-svg";
const out = {};
for (const f of readdirSync(dir).filter((x) => x.endsWith(".svg"))) {
  const name = f.replace(/\.svg$/, "");
  const svg = readFileSync(`${dir}/${f}`, "utf8");
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? "0 0 24 24";
  const paths = [];
  const re = /<(path|circle|rect|ellipse|line|polyline|polygon)\b([^>]*)\/?>/g;
  let m;
  while ((m = re.exec(svg))) {
    const attrs = {};
    const ar = /([a-zA-Z-]+)="([^"]*)"/g;
    let a;
    while ((a = ar.exec(m[2]))) attrs[a[1]] = a[2];
    paths.push({ tag: m[1], ...attrs });
  }
  out[name] = { viewBox, shapes: paths };
}
writeFileSync("src/components/icons.generated.ts", `// generated by scripts/build-icons.mjs — do not edit\nexport const GENERATED_ICONS: Record<string, { viewBox: string; shapes: Record<string, string>[] }> = ${JSON.stringify(out, null, 0)};\n`);
console.log(`wrote ${Object.keys(out).length} icons`);
